# default values for newsletter plugin
# please overwrite values in site/config/config.yml

newsletter_plugin:
  text_module:
    toolbar: 
      - 
        - ["Bold", "Italic"]
        - ["Link", "Unlink", "Image"]
        - ["BulletedList"]
        - ["Undo", "Redo"]
        - ["Format", "RemoveFormat", "Source"]
        
  # default sender name [only used as fallback if sender_email_addresses are not apropriatly configured with email/name]
  sender_name: rapila
  
  # used for confirmation e-mail, not to confuse with sender_email_addresses
  sender_email: 'newsletter@rapi.la'
  
  # Use this in your config.yml file to choose from different email addresses when sending
  sender_email_addresses:
    # 'noreply@example.com' : "Sender Name"
    # 'sender@example.com' : "Sender Name2"
    
    # - 'noreply@example.com' @deprecated, still works but is not recommended
  
  #requires_authentication options true, user_role rolekey, default: false
  unsubscribe_page: subscribe #a page identifier
  # comment > unsubscribe pages show all pages with NewsletterFrontendModule, check display_type
  
  opting_confirmation_required: true
  
  #how to convert to plain-text alternative set to null or false to send only html emails
  plain_text_alternative_method: markdown
  default_subscriber_group_id: 1 #anybody
