# default values for newsletter plugin
# please overwrite values in site/config/config.yml

newsletter_plugin:
  richtext_settings:
    height: 600
    toolbar_Full: [["Bold","Italic","-"],["Link","Unlink"],["BulletedList"],["Undo","Redo","-","RemoveFormat"],["Maximize","Styles","Format"],["Image", "PickImage"],["Source"]]
  sender_name: rapila
  
  # Use this in your config.yml file to choose from different email addresses when sending
  
  # sender_email_addresses:
  #   - 'noreply@example.com'
  
  #requires_authentication options true, user_role rolekey, default: false
  unsubscribe_page_name: subscribe

  subscriber_groups_require_authentication: 
    1: manager


